# Generated by Django 4.1 on 2024-06-23 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cate', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_cate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id_depe', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_depe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Escalafon',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_escala', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_usuario', models.CharField(max_length=255)),
                ('apel_usuario', models.CharField(max_length=255)),
                ('dni_usuario', models.CharField(max_length=20, unique=True)),
                ('correo_usuario', models.EmailField(max_length=254, unique=True)),
                ('password_usuario', models.CharField(max_length=255)),
                ('fechanac_usuario', models.DateField()),
                ('legajo_usuario', models.CharField(max_length=50, unique=True)),
                ('id_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento_app.categoria')),
                ('id_depe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento_app.dependencia')),
                ('id_escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento_app.escalafon')),
            ],
        ),
    ]
